import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";

import Nav from "@/components/Nav";
import "./globals.css";

const roboto = Roboto_Mono({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={roboto.className}>
        <Nav/>
        {children}
      </body>
    </html>
  )
}
