import type { Metadata } from "next";
import { nunito } from "./fonts";

import Nav from "@/components/Nav";
import "./globals.css";
import AOSInit from "@/components/AosInit";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <AOSInit/>
      <body className={nunito.className}>
        <Nav/>
        {children}
      </body>
    </html>
  )
}
